extend:
  - ../common_plot.yaml

RobotHardware0_q:
  func: plot_rad2deg
  data:
    - { log: RobotHardware0_q, column: [0-50] }

servo_pgain:
  data:
    - { log: RobotHardware0_pgainOut, column: [0-50] }

servo_dgain:
  data:
    - { log: RobotHardware0_dgainOut, column: [0-50] }

abst_new_ref_zmp:
  data:
    - { log: abst_originNewRefZmp, column: [0-2] }

abst_foot_origin_ref_cog:
  data:
    - { log: abst_footOriginRefCog, column: [0-2] }

abst_foot_origin_act_cog:
  data:
    - { log: abst_footOriginActCog, column: [0-2] }

abst_q:
  func: plot_rad2deg
  data:
    - { log: abst_q, column: [0-11] }

abst_refCogOut:
  data:
    - { log: abst_refCogOut, column: [0-2] }

abst_refCogVelOut:
  data:
    - { log: abst_refCogVelOut, column: [0-2] }

abst_refCogAccOut:
  data:
    - { log: abst_refCogAccOut, column: [0-2] }

abst_refZmpOut:
  data:
    - { log: abst_refZmpOut, column: [0-2] }

abst_baseOriginRefZmp:
  data:
    - { log: abst_baseOriginRefZmp, column: [0-2] }

abst_basePos:
  data:
    - { log: abst_baseTformOut, column: [0-2] }

abst_refAngularMomentumRPY:
  data:
    - { log: abst_refAngularMomentumRPY, column: [0-2] }

abst_refContactStates:
  data:
    - { log: abst_refContactStates, column: [0-10] }

abst_legtraj:
  data:
    - { log: abst_controlSwingSupportTime, column: [0-5] }
