main:
  rleg_joint_angle:
    legends:
      - { key: sh_qOut, id: [0-5] }
      - { key: abst_q, id: [0-5] }
      # - { key: st_q, id: [0-5] }
      - { key: RobotHardware0_q, id: [0-5] }

  lleg_joint_angle:
    legends:
      - { key: sh_qOut, id: [6-11] }
      - { key: abst_q, id: [6-11] }
      # - { key: st_q, id: [6-11] }
      - { key: RobotHardware0_q, id: [6-11] }

  ref_zmp:
    legends:
      - { key: abst_refZmpOut, id: [0-2] }
    newline: false

  base_zmp:
    legends:
      - { key: abst_baseOriginRefZmp, id: [0-2] }

  world_ref_cog:
    legends:
      - { key: abst_refCogOut, id: [0-2] }
    newline: false

  abst_pos:
    legends:
      - { key: abst_basePos, id: [0-2] }

  # foot_origin_cog:
  #   legends:
  #     - { key: abs_foot_origin_ref_cog, id: [0-2] }
  #     - { key: abs_foot_origin_act_cog, id: [0-2] }


  # tracking:
  #   legends:
  #     - {key: rh_st_diff, id: [0-5] }
  #     - {key: abs_enc_diff, id: [0-5] }

  # right_foot_force:
  #   legends:
  #     - { key: sh_rfsensorOut, id: [0-5] }
  #     - { key: RobotHardware0_rfsensor, id: [0-5] }
  #     - { key: rmfo_off_rfsensor, id: [0-5] }

  # current:
  #   legends:
  #     - { key: current, id: [0-5] }

  # imu_gsensor:
  #   legends:
  #     - { key: imu_gsensor, id: [0], label: x }
  #     - { key: imu_gsensor, id: [1], label: y }
  #     - { key: imu_gsensor, id: [2], label: z }
  #   newline: False

  # imu_gyrometer:
  #   legends:
  #     - { key: imu_gyrometer, id: [0], label: x }
  #     - { key: imu_gyrometer, id: [1], label: y }
  #     - { key: imu_gyrometer, id: [2], label: z }

  # temperature:
  #   legends:
  #     - { key: motor_temp, id: [0-5] }
  #     - { key: motor_outer_temp, id: [0-5] }

  # comp:
  #   legends:
  #     - { key: comp, id: [0-5] }

  # watt:
  #   legends:
  #     - { key: watt, id: [0-5] }

  # ServoState:
  #   legends:
  #     - { key: ServoState, id: [0-5] }

  # 12V:
  #   legends:
  #     - { key: 12V, id: [0,1,2,3,4,5] }

  # 80V:
  #   legends:
  #     - { key: 80V, id: [0,1,2,3,4,5] }

  # ZMP:
  #   legends:
  #     - { key: st_zmp, id: [0,1] }
