extend:
  - ../../common_plot.yaml

sh_qOut:
  func: plot_rad2deg
  data:
    - { log: sh_qOut, column: [0-11] }

abc_q:
  func: plot_rad2deg
  data:
    - { log: abc_q, column: [0-11] }

st_q:
  func: plot_rad2deg
  data:
    - { log: st_q, column: [0-11] }

st_qSTRef:
  func: plot_rad2deg
  data:
    - { log: st_qSTRef, column: [0-11] }

RobotHardware0_q:
  func: plot_rad2deg
  data:
    - { log: RobotHardware0_q, column: [0-11] }

rh_st_diff:
  func: plot_rh_q_st_q
  data:
    - { log: RobotHardware0_q, column: [0-11] }
    - { log: st_q, column: [0-11] }

abs_enc_diff:
  func: plot_abs_enc
  data:
    - { log: RobotHardware0_servoState, column: [0-11] }
    - { log: RobotHardware0_servoState, column: [0-11] }
current:
  func: plot_current
  data:
    - { log: RobotHardware0_servoState, column: [0,1,2,3,4,5] }

motor_temp:
  func: plot_motor_temp
  data:
    - { log: RobotHardware0_servoState, column: [0,1,2,3,4,5] }

motor_outer_temp:
  func: plot_motor_outer_temp
  data:
    - { log: RobotHardware0_servoState, column: [0,1,2,3,4,5] }

comp:
  func: plot_comp
  data:
    -  { log: st_allEEComp, column: [0, 1, 2, 3, 4, 5] }

watt:
  func: plot_watt
  data:
    - { log: RobotHardware0_dq, column: [0,1,2,3,4,5]  }
    - { log: RobotHardware0_tau, column: [0,1,2,3,4,5] }
ServoState:
  func: plot_servostate
  data:
    - { log: RobotHardware0_servoState, column: [0,1,2,3,4,5] }

12V:
  func: plot_12V
  data:
    - { log: RobotHardware0_servoState, column: [0,1,2,3,4,5] }

80V:
  func: plot_80V
  data:
    - { log: RobotHardware0_servoState, column: [0,1,2,3,4,5] }

pgain:
  func: plot_pgain
  data:
    - { log: RobotHardware0_servoState, column: [0-11] }

dgain:
  func: plot_dgain
  data:
    - { log: RobotHardware0_servoState, column: [0-11] }

abs_new_ref_zmp:
  data:
    - { log: abc_originNewRefZmp, column: [0-2] }

abs_foot_origin_ref_cog:
  data:
    - { log: abc_footOriginRefCog, column: [0-2] }

abs_foot_origin_act_cog:
  data:
    - { log: abc_footOriginActCog, column: [0-2] }

abst_q:
  func: plot_rad2deg
  data:
    - { log: abst_q, column: [0-11] }

abst_refCogOut:
  data:
    - { log: abst_refCogOut, column: [0-2] }

abst_refCapturePoint:
  data:
    - { log: abst_refCapturePoint, column: [0-2] }

abst_refZmpOut:
  data:
    - { log: abst_refZmpOut, column: [0-2] }

abst_refZmpXY:
  func: plot_xy
  data:
    - { log: abst_refZmpOut, column: [1] }
    - { log: abst_refZmpOut, column: [0] }

abst_baseOriginRefZmp:
  data:
    - { log: abst_baseOriginRefZmp, column: [0-2] }

abst_basePos:
  data:
    - { log: abst_baseTformOut, column: [0-2] }

abst_refContactStates:
  data:
    - { log: abst_refContactStates, column: [0-10] }

abst_legtraj:
  data:
    - { log: abst_controlSwingSupportTime, column: [0-5] }
